run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gofmt
    - goimports
    - revive
  disable:
    - depguard

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
      - name: blank-imports
      - name: context-as-argument
      - name: error-return
      - name: error-strings
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
  goimports:
    local-prefixes: github.com/cloudlayerio/cloudlayerio-go

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
